### PR TITLE
Added template_param helper for rails with Railtie.

### PR DESCRIPTION
**Pull request by opodartho**
Instead of asking user to add template_param helper in ApplicationHelper gem should provide one.

### CODE REVIEW

**Comment by jaredbeck** [comment]
Asking users to add their own helper was a deliberate decision. It gives users a place to change the behavior of their helper. Also, I want this library to be totally decoupled from rails.

**Comment by jaredbeck** [comment]
Perhaps there could be a gem, like `template_params-rails` that glues them together?

**Comment by opodartho** [comment]
Making another gem that glues with rails is better approach.

**Comment by jaredbeck** [comment]
> Making another gem that glues with rails is better approach.

If you want to make a gem like that, feel free to use it in CDJ :)

**Pull request closed without merging**
